name: Tests
on:
  pull_request:
  push:
    branches:
      - v2
      - v0.52.x
      - v0.50.x

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test-minid:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test block creation
        run: |
          make install
          make init
          minid start &
          MINID_PID=$!
          cnt=0
          while ! minid query block --type=height 5; do
            cnt=$((cnt + 1))
            if [ $cnt -gt 30 ]; then
              kill -9 "$MINID_PID"
              exit 1
            fi
            sleep 1
          done
          kill -9 "$MINID_PID"
